apiVersion: apps/v1
kind: Deployment
metadata:
  name: sak
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: sak
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: sak
    spec:
      containers:
      - name: sak
        image: leodotcloud/swiss-army-knife:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: shynet-env
        - secretRef:
            name: shynet-secret
        - secretRef:
            name: postgres-secret
