apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  postgres-db: postgres
  postgresql.conf: |
    max_connections = 1000
    work_mem = 4MB
    shared_buffers = 2048MB
