apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-restore
  namespace: REPLACE_ME
  labels:
    app.kubernetes.io/name: backup-restore
    app.kubernetes.io/part-of: REPLACE_ME
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: backup-restore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backup-restore
        app.kubernetes.io/part-of: REPLACE_ME
    spec:
      containers:
      - image: REPLACE_ME
        name: backup-restore
        imagePullPolicy: IfNotPresent
        command: ["wait.bb"]
        env: []
        volumeMounts: []
      volumes: []