apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  annotations: {}
spec:
  tls:
    - hosts:
        - FQDN
      secretName: c4k-common-cert
  rules:
    - host: FQDN
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: SERVICE_NAME
                port:
                  number: 80
