apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus
  name: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      serviceAccountName: prometheus
      enableServiceLinks: true
      containers:
        - name: prometheus
          image: "quay.io/prometheus/prometheus:v3.4.0"
          imagePullPolicy: "IfNotPresent"
          args: 
            - REPLACEME
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
              readOnly: true
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          secret:
            secretName: prometheus-conf
            defaultMode: 420
