apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
  ports:
  - name: prometheus-http
    protocol: TCP
    port: 9000
    targetPort: 9090
