apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-pushgateway